server:
  port: 8081

spring:
  application:
    name: product
  mongodb:
    uri: mongodb://localhost:27017/product_db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/f2a31af8-f420-417d-b585-34f31769c272/v2.0

app:
  security:
    audience: 8d14a1ab-3758-45e4-b409-a95f6b7442e3
  cors:
    allowed-origins: http://localhost:4200